### ISSUE TITLE
JTE 1.2 Fails when Jenkinsfile is missing

### ISSUE THREAD

**Issue by theeltahir** [boozallen/jenkins-templating-engine#45]
After upgrading to JTE 1.2 the JTE plugin fails on repositories using the `pipeline_template = "template_name.groovy"`

```
[JTE] Obtained Repository Jenkinsfile 
[JTE] -- scm: git ssh://git@coderepo/ltc/colors-app.git
[JTE] -- file path: Jenkinsfile
[Pipeline] End of Pipeline
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/ltc/repos/colors-app/browse/Jenkinsfile?at=master&start=0&limit=500
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:792)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1042)
	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.boozallen.plugins.jte.utils.FileSystemWrapper.getFileContents(FileSystemWrapper.groovy:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at org.boozallen.plugins.jte.TemplateEntryPointVariable.getTemplate(TemplateEntryPointVariable.groovy:145)
	at org.boozallen.plugins.jte.TemplateEntryPointVariable$getTemplate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at script15645120304811015047032.call(script15645120304811015047032.groovy:31)
	at WorkflowScript.run(WorkflowScript:1)
	at ___cps.transform___(Native Method)
...
```

We are using the  `Bitbucket Branch Source Plugin 2.4.5`, this maybe related to the new `FileSystemWrapper` implemntation in the 1.2 plugin
Once we added a blank Jenkinsfile to the root of the project, but this seems to defeat the purpose of using the `pipeline_template` function

**Comment by cokieffebah** [comment]
what was your previous version of JTE? @theeltahir

**Comment by theeltahir** [comment]
we were previously using v1.1.1

**Comment by cokieffebah** [comment]
how long has your code been using this ${pipeline_template}.groovy configuration?

**Comment by theeltahir** [comment]
hmmm that is interesting. we recently started experimenting with JTE as of v1.1.1 as far as i know it always worked in this fashion.

I just downgraded the plugin and tried again and this is what i see in the logs

```
[JTE] Obtained Repository Jenkinsfile Jenkinsfile from git ssh://git@coderepo:7999/ltc/colors-app.git
[JTE] exception java.io.FileNotFoundException: URL: /rest/api/1.0/projects/ltc/repos/colors-app/browse/Jenkinsfile?at=master&start=0&limit=500 for Jenkinsfile from git ssh://git@coderepo:7999/ltc/colors-app.git
[JTE] Obtained Pipeline Template pipeline_templates/ltc_test.groovy from git https://coderepo/scm/ltc/jte-configuration.git
```

**Comment by cokieffebah** [comment]
hmm, let me check the 1.1.1 codebase, that is not what I expected ^^

**Comment by cokieffebah** [comment]
can you include the next few lines of that 1.1.1 log? thanks

**Comment by theeltahir** [comment]
```
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor
Agent default-bkjs4 is provisioned from template Kubernetes Pod Template
Running on default-bkjs4 in /home/jenkins/workspace/LTC_colors-app_master
[Pipeline] {
[JTE][Step - bitbucket/withGit.call(CpsClosure2)]
[Pipeline] checkout
using credential JENKINS_SSHKEY
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository ssh://git@coderepo:7999/ltc/colors-app.git
```

**Comment by theeltahir** [comment]
looking into the source code (I am a groovy/jenkins noobie so forgive me) looks like the exception is thrown here:
https://github.com/boozallen/jenkins-templating-engine/blob/master/src/main/groovy/org/boozallen/plugins/jte/utils/FileSystemWrapper.groovy#L89

So for some reason Bitbucket plugin does not honor the `if (!f.exists()) {` condition and the exception is not properly caught by the `FileSystemWrapper` class. is it possible to add a catch for the `java.io.FileNotFoundException` exception to allow the pipeline to continue?

**Comment by cokieffebah** [comment]
The simple solution is to change your pipeline_template's name to remove the '.groovy' and see if that works. can you try that first?  If not then it is a problem with bitbucket retrieving the file for the template repo.

**Comment by theeltahir** [comment]
I think there has been a miscommunication.
there is no issue with `pipeline_template = "template_name.groovy"` on 1.1.1 or 1.2

The issue we are facing is:
colors-app repo has `pipeline_template = "template_name.groovy"` declared in pipeline_config.groovy
however it does not have a Jenkinsfile in the root of the repo
in JTE 1.1.1 this worked just fine
in JTE 1.2 this throws an exception as it tried to download a Jenkinsfile that does not exist
to solve this temporarily I created an empty Jenkinsfile in the root of the colors-app repo and it works as previous

**Comment by cokieffebah** [comment]
ah, got it. sorry about that.  I will see if I can replicate this situation.  will attempt that replication in the next 24 hours. thanks again

**Comment by cokieffebah** [comment]
looking through: 
https://github.com/jenkinsci/scm-api-plugin/blob/master/src/main/java/jenkins/scm/api/SCMFile.java

and (I am assuming this is the bitbucket SCM)

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFile.java
and
https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/jenkins/plugins/git/GitSCMFile.java

...
BitbucketSCMFile does not appear to properly use Type.NONEXISTENT which is what SCMFile.exists() checks from the getType() property; when BitbucketSCMFile returns from newChild(...) (called by SCMFile.child)  it only uses DIRECTORY or FILE as types unlike GitSCMFile.getType()

**Comment by cokieffebah** [comment]
we will implement a fix and check for FileNotFoundException.  Thanks @theeltahir

**Comment by cokieffebah** [comment]
https://github.com/jenkinsci/templating-engine-plugin/pull/11

**Comment by cokieffebah** [comment]
@theeltahir could you fill out this info so I can submit an issue against the bitbucket scm implementation:

### Your checklist for this issue

- [ ] Jenkins version

- [ ] Plugin version

- [ ] Bitbucket cloud

- [ ] Bitbucket server and version

**Comment by theeltahir** [comment]
Hey @cokieffebah Thanks for the quick turn around on this issue
Jenkins Version: 2.176.2
Plugin Version: Bitbucket Branch Source Plugin 2.4.5
Bitbucket Server Version: Atlassian Bitbucket v6.2.0

**Comment by cokieffebah** [comment]
FYI, active development is against this repo: https://github.com/jenkinsci/templating-engine-plugin

**Comment by cokieffebah** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/212

**Comment by theeltahir** [comment]
Fantastic! for future reference do i open Issues against the Jenkinsci repo instead of this one?

**Comment by cokieffebah** [comment]
That would be best.  and Thanks for basically pointing out the exact problem

**Comment by steven-terrana** [comment]
@theeltahir - we released Templating Engine 1.3 yesterday that incorporates a handling of FileNotFoundException's caused by the BitBucket Branch Source plugin. 

can you please give this version a shot and see if it resolves your issue? 

i will be closing this issue and disabling issues on this repository, please feel free to open a new issue on https://github.com/jenkinsci/templating-engine-plugin if the issue is not resolved.
